# Generated by Django 3.2.5 on 2021-07-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        ('comments', '0004_rename_mptt_level_comment_level'),
    ]

    operations = [
    ]
