# Generated by Django 3.2.5 on 2021-07-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0002_moderator_user'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='sub_reddits',
            field=models.ManyToManyField(blank=True, null=True, to='subreddit.SubReddit'),
        ),
    ]
