# Generated by Django 3.2.5 on 2021-07-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0002_moderator_user'),
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subreddit.subreddit'),
        ),
    ]
