# Generated by Django 3.2.5 on 2021-07-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_auto_20210715_1607'),
        ('post_app', '0002_initial'),
    ]

    operations = [
    ]
