# Generated by Django 3.2.5 on 2021-07-16 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0002_moderator_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0003_merge_0002_auto_20210715_1607_0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subreddit.subreddit'),
        ),
    ]
