# Generated by Django 3.2.5 on 2021-07-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_auto_20210708_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='img',
            new_name='Main_img',
        ),
    ]
