# Generated by Django 3.2.5 on 2021-07-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_rename_img_images_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Main_img',
            new_name='hotel_Main_img',
        ),
    ]
