# Generated by Django 3.2.5 on 2021-07-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_rename_main_img_images_hotel_main_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='downvote',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upvote',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('Text', 'Text'), ('Link', 'Link'), ('Image', 'Image')], default='Text', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_post',
            field=models.URLField(blank=True, null=True),
        ),
    ]
